from typing import Any, Literal, TypedDict

AgentScope = Literal['messages:read', 'attachments:read', 'drafts:write', 'messages:send', 'events:read', 'senders:write']
class Inbox(TypedDict):
    id: str
    email: str
    name: str
class Credential(TypedDict):
    id: str
    key: str
class _RequiredInbox(TypedDict):
    name: str
    username: str
class CreateInbox(_RequiredInbox, total=False):
    mode: Literal['read', 'drafts', 'send']
    sendAllow: list[str]
    senderManagementMode: Literal['none', 'restricted', 'any']
    senderManagementAllow: list[str]
class Draft(TypedDict, total=False):
    to: list[str]
    cc: list[str]
    bcc: list[str]
    subject: str
    text: str
    attachments: list[dict[str, str]]
    replyToId: str
    version: int
class ExpectboxAgent:
    def __init__(self, api_key: str, base_url: str = ..., timeout: float = ...) -> None: ...
    def inboxes(self) -> dict[str, list[Inbox]]: ...
    def messages(self, inbox: str, **query: Any) -> dict[str, Any]: ...
    def message(self, inbox: str, message: str) -> dict[str, Any]: ...
    def thread(self, inbox: str, thread: str) -> dict[str, Any]: ...
    def attachment(self, inbox: str, attachment: str) -> bytes: ...
    def draft(self, inbox: str, body: Draft) -> dict[str, Any]: ...
    def edit_draft(self, inbox: str, draft: str, body: Draft) -> dict[str, Any]: ...
    def send(self, inbox: str, body: Draft, idempotency_key: str) -> dict[str, str]: ...
    def reply(self, inbox: str, message: str, body: Draft, idempotency_key: str) -> dict[str, str]: ...
    def events(self, cursor: str = ...) -> dict[str, Any]: ...
    def senders(self, inbox: str) -> dict[str, Any]: ...
    def allow_sender(self, inbox: str, match_type: Literal['email','domain'], match_value: str, reason: str) -> dict[str, Any]: ...
class ExpectboxProject:
    def __init__(self, api_key: str, base_url: str = ..., timeout: float = ...) -> None: ...
    def project(self) -> dict[str, Any]: ...
    def inboxes(self) -> dict[str, list[Inbox]]: ...
    def create_inbox(self, body: CreateInbox, idempotency_key: str) -> Inbox: ...
    def create_inbox_key(self, inbox: str, name: str, scopes: list[AgentScope], days: int = ...) -> Credential: ...
    def revoke_inbox_key(self, inbox: str, key: str) -> dict[str, bool]: ...
